# Generated by Django 5.1.2 on 2024-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_menuitem_menuitemingredient_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
