# Generated by Django 5.1.2 on 2024-11-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_name_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='IngredientTag',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='tags',
            new_name='ingredient_tags',
        ),
    ]
