from django.core.management.base import BaseCommand
from menu.models import Ingredient

class Command(BaseCommand):
    help = "Populate the database with initial menu data"

    def handle(self, *args, **options):

        Ingredients = [
            Ingredient(name="Spaghetti", quantity_in_stock=20000, unit="grams"),
            Ingredient(name="Pancetta", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Eggs", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Parmesan Cheese", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Pecorino Romano Cheese", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Garlic", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Black Pepper", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Salt", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Olive Oil", quantity_in_stock=10000, unit="milliliters"),
            Ingredient(name="Fettuccine", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Heavy Cream", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Butter", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Penne Pasta", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Tomato Sauce", quantity_in_stock=20000, unit="grams"),
            Ingredient(name="Red Chili Flakes", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Parsley", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Lasagna Noodles", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Ground Beef", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Ricotta Cheese", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Mozzarella Cheese", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Marinara Sauce", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Italian Seasoning", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Ravioli", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Spinach", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Mixed Vegetables", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Linguine", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Fresh Clams", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="White Wine", quantity_in_stock=10000, unit="milliliters"),
            Ingredient(name="Tortellini", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Basil Pesto", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Pine Nuts", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Gnocchi", quantity_in_stock=8000, unit="grams"),
            Ingredient(name="Chicken Breast", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Honey", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Soy Sauce", quantity_in_stock=3000, unit="milliliters"),
            Ingredient(name="Lemon Juice", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Mixed Herbs", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Marsala Wine", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="BBQ Sauce", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Curry Powder", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Cream", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Cajun Seasoning", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Tomatoes", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Onions", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Bell Peppers", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Beef", quantity_in_stock=20000, unit="grams"),
            Ingredient(name="Filet Mignon", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Ribeye", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="T-Bone", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Sirloin", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Mushrooms", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Peppercorns", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Quinoa", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Chickpeas", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Tofu", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Rice", quantity_in_stock=20000, unit="grams"),
            Ingredient(name="Falafel", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Eggplant", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Lentils", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Dairy-Free Cheese", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Bulgogi Marinade", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Naan Bread", quantity_in_stock=200, unit="pieces"),
            Ingredient(name="Rice Noodles", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Gyro Meat", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Shrimp", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Tacos Shells", quantity_in_stock=500, unit="pieces"),
            Ingredient(name="Sushi Rice", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Pickled Vegetables", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Pork", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Seafood", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Chili Sauce", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Ribs", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Lamb Chops", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Pork Belly", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Chicken Wings", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Assorted Vegetables", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Sausages", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Beef Skewers", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Portobello Mushrooms", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Herbs", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Potatoes", quantity_in_stock=20000, unit="grams"),
            Ingredient(name="Ziti Pasta", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Meatloaf Mix", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Gravy", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Beans", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Cheddar Cheese", quantity_in_stock=7000, unit="grams"),
            Ingredient(name="Basil", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Pepperoni", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Red Onions", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Pineapple", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Sausage", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Fresh Mushrooms", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Shredded Chicken", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Fried Fish", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Grilled Shrimp", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Plant-Based Meat", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Flour", quantity_in_stock=25000, unit="grams"),
            Ingredient(name="Sugar", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Baking Powder", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Baking Soda", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Vanilla Extract", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Cinnamon", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Nutmeg", quantity_in_stock=250, unit="grams"),
            Ingredient(name="Cumin", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Paprika", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Oregano", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Thyme", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Rosemary", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Bay Leaves", quantity_in_stock=100, unit="grams"),
            Ingredient(name="Chili Powder", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Turmeric", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Ginger", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Cardamom", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Cloves", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Coriander", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Mustard Seeds", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Fennel Seeds", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Sesame Seeds", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Poppy Seeds", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Cayenne Pepper", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Red Pepper Flakes", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Allspice", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Sage", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Tarragon", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Dill", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Cilantro", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Mint", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Chives", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Scallions", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Leeks", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Shallots", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Celery", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Carrots", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Zucchini", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Squash", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Broccoli", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Cauliflower", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Asparagus", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Green Beans", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Peas", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Corn", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Brussels Sprouts", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Cabbage", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Kale", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Swiss Chard", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Collard Greens", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Arugula", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Watercress", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Radishes", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Beets", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Turnips", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Parsnips", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Sweet Potatoes", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Yams", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Rutabaga", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Artichokes", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Fennel", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Okra", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Tomatillos", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Jalapenos", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Serrano Peppers", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Habanero Peppers", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Poblano Peppers", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Anaheim Peppers", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Banana Peppers", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Ghost Peppers", quantity_in_stock=100, unit="grams"),
            Ingredient(name="Scotch Bonnet Peppers", quantity_in_stock=300, unit="grams"),
            Ingredient(name="Capers", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Olives", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Sun-Dried Tomatoes", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Raisins", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Dried Cranberries", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Dried Apricots", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Dates", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Figs", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Prunes", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Coconut Milk", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Almond Milk", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Soy Milk", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Oat Milk", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Coconut Oil", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Sesame Oil", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Avocado Oil", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Grapeseed Oil", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Peanut Oil", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Walnut Oil", quantity_in_stock=500, unit="milliliters"),
            Ingredient(name="Truffle Oil", quantity_in_stock=250, unit="milliliters"),
            Ingredient(name="Vegetable Oil", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Fish Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Oyster Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Hoisin Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Sriracha Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Worcestershire Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Tabasco Sauce", quantity_in_stock=500, unit="milliliters"),
            Ingredient(name="Miso Paste", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Tahini", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Nutritional Yeast", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Chicken Thighs", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Salmon", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="White Fish Fillets", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Clams", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Mussels", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Saffron", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Crab Meat", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Mayonnaise", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Mustard", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Lobster Tail", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Arborio Rice", quantity_in_stock=15000, unit="grams"),
            Ingredient(name="Breadcrumbs", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Ribeye Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="T-Bone Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Sirloin Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Beef Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="New York Strip Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Bistro Steak", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Cucumber", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Avocado", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Vegetable Broth", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Flour Tortillas", quantity_in_stock=50, unit="pcs"),
            Ingredient(name="Corn Tortillas", quantity_in_stock=50, unit="pcs"),
            Ingredient(name="Black Beans", quantity_in_stock=1500, unit="grams"),
            Ingredient(name="Guacamole", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Salsa", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Lettuce", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Hummus", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Tabbouleh", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Macaroni Pasta", quantity_in_stock=10000, unit="grams"),
            Ingredient(name="Milk", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Garlic Powder", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Beef Broth", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Ketchup", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pie Crust", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Kidney Beans", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pizza Dough", quantity_in_stock=2000, unit="pcs"),
            Ingredient(name="Gorgonzola Cheese", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Ham", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Buffalo Sauce", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Taco Shells", quantity_in_stock=100, unit="pcs"),
            Ingredient(name="Sour Cream", quantity_in_stock=3000, unit="milliliters"),
            Ingredient(name="Lime", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pulled Pork", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Burger Bun", quantity_in_stock=100, unit="pcs"),
            Ingredient(name="Tomato", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Bacon", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Swiss Cheese", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Beef Patty", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Pickles", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Veggie Patty", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pepper Jack Cheese", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pineapple Slice", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Teriyaki Sauce", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Blue Cheese", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Yogurt", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Bean Sprouts", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Peanuts", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Pita Bread", quantity_in_stock=100, unit="pcs"),
            Ingredient(name="Tzatziki Sauce", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Nori Sheets", quantity_in_stock=100, unit="pcs"),
            Ingredient(name="Wasabi", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Vinegar", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Tahini Sauce", quantity_in_stock=2000, unit="milliliters"),
            Ingredient(name="Chicken Broth", quantity_in_stock=5000, unit="milliliters"),
            Ingredient(name="Prosciutto", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Puff Pastry", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Beef Tenderloin", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Short Rib Filling", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Lobster Meat", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Fig Jam", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Brioche", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Foie Gras", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Chicken Stock", quantity_in_stock=4000, unit="milliliters"),
            Ingredient(name="Wagyu Beef", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Sea Bass Fillets", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Lamb", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Duck Fat", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Duck Legs", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Skewers", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Onion Powder", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Beef Brisket", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Pork Ribs", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Veal Shanks", quantity_in_stock=5000, unit="grams"),
            # Additional
            Ingredient(name="Parmesan", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Croutons", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Caesar Dressing", quantity_in_stock=1500, unit="milliliters"),
            Ingredient(name="Anchovy Paste", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Feta Cheese", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Kalamata Olives", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Fresh Mozzarella", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Basil Leaves", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Balsamic Reduction", quantity_in_stock=500, unit="milliliters"),
            Ingredient(name="Carrot", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Bell Pepper", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Napa Cabbage", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Red Cabbage", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Green Onion", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Soy-Ginger Dressing", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Cream Cheese", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Spring Roll Wrappers", quantity_in_stock=500, unit="pcs"),
            Ingredient(name="Bacon Bits", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Vanilla Ice Cream", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Chocolate Ice Cream", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Strawberry Ice Cream", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Mint Chocolate Chip", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Rocky Road Ice Cream", quantity_in_stock=5000, unit="grams"),
            Ingredient(name="Cocoa Powder", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Graham Crackers", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Apples", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Lemon Zest", quantity_in_stock=200, unit="grams"),
            Ingredient(name="Chocolate", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Coffee", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Herbal Tea Bag", quantity_in_stock=500, unit="pcs"),
            Ingredient(name="Whipped Cream", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Coke", quantity_in_stock=200, unit="milliliters"),
            Ingredient(name="Sprite", quantity_in_stock=200, unit="milliliters"),
            Ingredient(name="Ginger Ale", quantity_in_stock=200, unit="milliliters"),
            Ingredient(name="Root Beer", quantity_in_stock=200, unit="milliliters"),
            Ingredient(name="Lemonade", quantity_in_stock=200, unit="milliliters"),
            Ingredient(name="Balsamic Vinegar", quantity_in_stock=1000, unit="milliliters"),
            Ingredient(name="Red Wine Vinegar", quantity_in_stock=500, unit="milliliters"),
            Ingredient(name="Romaine Lettuce", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Tuna", quantity_in_stock=500, unit="grams"),
            Ingredient(name="Mixed Salad Greens", quantity_in_stock=3000, unit="grams"),
            Ingredient(name="Cherry Tomatoes", quantity_in_stock=2000, unit="grams"),
            Ingredient(name="Red Bell Pepper", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Green Peas", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Couscous", quantity_in_stock=1000, unit="grams"),
            Ingredient(name="Pearl Barley", quantity_in_stock=1000, unit="grams"),

        ]

        Ingredient.objects.bulk_create(Ingredients, batch_size=100)

        # Print success message
        self.stdout.write(self.style.SUCCESS("Inredients populated successfully."))